ingress-nginx:
  controller:
    name: controller
    image:
      repository: k8s.gcr.io/ingress-nginx/controller
      tag: "v0.49.3"
      digest: sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a
      pullPolicy: IfNotPresent
      # www-data -> uid 101
      runAsUser: 101
      allowPrivilegeEscalation: true
    config:
      client-body-timeout: 60
      client-header-timeout: 60
      custom-http-errors: 403,404,500,503
      enable-ocsp: "true"
      hide-headers: X-Powered-By,Server
      hsts-preload: "true"
      keep-alive: 10
      large-client-header-buffers: 4 8k
      log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
        "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user":
        "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status,
        "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query":
        "$args", "request_length": $request_length, "duration": $request_time,"method":
        "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent",
        "ssl_client_s_dn": "$ssl_client_s_dn" }'
      proxy-body-size: 1m
      server-tokens: "false"
      use-proxy-protocol: "true"
    addHeaders:
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-XSS-Protection: 1; mode=block
  ## Optional array of imagePullSecrets containing private registry credentials
  ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets:
  - name: registry-access
